// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {officialdetect} from '../models';

export function AdoptInstallDir(arg1:string):Promise<officialdetect.Install>;

export function OfficialState():Promise<officialdetect.State>;

export function OpenDownloadPage():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function PickInstallDir():Promise<officialdetect.Install>;
