// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptInstallDir(arg1) {
  return window['go']['main']['App']['AdoptInstallDir'](arg1);
}

export function OfficialState() {
  return window['go']['main']['App']['OfficialState']();
}

export function OpenDownloadPage() {
  return window['go']['main']['App']['OpenDownloadPage']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickInstallDir() {
  return window['go']['main']['App']['PickInstallDir']();
}
