// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSkippedCore():Promise<string>;

export function GetCoreVersions():Promise<main.coreVersionsView>;

export function GetUpdateStatus():Promise<string>;

export function HasPluginInstaller():Promise<boolean>;

export function InstallBundledPlugins():Promise<string>;

export function OpenBrowser():Promise<void>;

export function Quit():Promise<void>;

export function Restart():Promise<void>;

export function Retry():Promise<void>;

export function SkipCoreVersion(arg1:string):Promise<string>;

export function UpdateCore(arg1:string):Promise<string>;
