// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSkippedCore() {
  return window['go']['main']['App']['ClearSkippedCore']();
}

export function GetCoreVersions() {
  return window['go']['main']['App']['GetCoreVersions']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function Retry() {
  return window['go']['main']['App']['Retry']();
}

export function SkipCoreVersion(arg1) {
  return window['go']['main']['App']['SkipCoreVersion'](arg1);
}

export function UpdateCore(arg1) {
  return window['go']['main']['App']['UpdateCore'](arg1);
}
