// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function Retry() {
  return window['go']['main']['App']['Retry']();
}
