// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUpdateStatus():Promise<string>;

export function OpenBrowser():Promise<void>;

export function Quit():Promise<void>;

export function Restart():Promise<void>;

export function Retry():Promise<void>;
